version: '3.9'

services:
  php-fpm:
    image: php:8.2-fpm
    container_name: landona-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

networks:
  proxy:
    external: true
