version: "3.7"
services:
  app:
    build:
      args:
        user: taylor
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: landona
    container_name: landona-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - nginx-proxy
    environment:
      VIRTUAL_HOST: landona.com.au
      VIRTUAL_PORT: 3001
      LETSENCRYPT_HOST: landona.com.au
      LETSENCRYPT_EMAIL: taylorivanoff@gmail.com
    expose:
      - 3001

networks:
  nginx-proxy:
    external: true
