services:
  app:
    build:
      args:
        user: taylor
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: landona
    container_name: landona-app
    restart: unless-stopped
    volumes:
      - ./:/usr/share/nginx/html:ro
    networks:
      - proxy
    environment:
      - VIRTUAL_HOST=landona.com.au
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=landona.com.au
      - LETSENCRYPT_EMAIL=taylorivanoff@gmail.com
    expose:
      - "80"

networks:
  nginx-proxy:
    external: true
