services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: landona
    container_name: landona-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - nginx-reverse-proxy

  nginx:
    image: nginx:alpine
    container_name: landona-nginx
    restart: unless-stopped
    ports:
      - "8585:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - nginx-reverse-proxy
    environment:
      VIRTUAL_PORT: 8585
      VIRTUAL_HOST: landona.com.au
      LETSENCRYPT_HOST: landona.com.au

networks:
  nginx-reverse-proxy:
    external: true
