services:
  app:
    build:
      args:
        user: taylor
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: landona
    container_name: landona-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - proxy
    environment:
      VIRTUAL_HOST: landona.com.au
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: landona.com.au
      LETSENCRYPT_EMAIL: taylorivanoff@gmail.com
    expose:
      - "80"

networks:
  proxy:
    external:
      name: nginx-proxy
