version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app.conf:/etc/nginx/conf.d
      - app:/var/www/html
    depends_on:
      - php-fpm

  php-fpm:
    image: php:latest
    volumes:
      - app:/var/www/html
    working_dir: /var/www/html
#    depends_on:
#      - mysql

#  mysql:
#    image: mysql:latest
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: your_root_password
#      MYSQL_DATABASE: your_database_name
#      MYSQL_USER: your_database_user
#      MYSQL_PASSWORD: your_database_password
#    volumes:
#      - mysql-data:/var/lib/mysql

volumes:
  app:
#  mysql-data:
