version: "3.7"
services:
  app:
    build:
      args:
        user: taylor
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: landona
    container_name: landona-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - landona

networks:
  landona:
    driver: bridge
