version: "3.7"
services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: landona
    container_name: landona-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:alpine
    container_name: landona-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
