<?php

return [
    'purchase' => [
        'Pre Exchange',
        'Cost Agreement',
        'Check Names',
        'VOI',
        'PEXA form',
        'Declaration',
        'Send client in an email',
        'Post Exchange',
        'First Home Buyer',
        'Stewart title',
        'Tenancy',
        'Setup PEXA Workspace',
        'Transfer',
        'Mortgagee',
        'Section 47',
        'FRCGWCC',
        'Requisitions',
        'Section 184',
        'Section 22',
        'Searches',
        'Stamp Duty',
        'Settlement',
        'Update certificates',
        'PEXA',
        'Order on the agent',
        'Pre Settlement',
        'Invoice',
    ],
    'sale' => [
        'Pre Exchange',
        'Edit',
        'Email to Clients',
        'Docusign',
        'Order Searches',
        'Email to Agent',
        'Strata Report',
        'Prepare Contract',
        'Post Exchange',
        'Requisitions',
        'Section 22',
        'Discharge Mortgage',
        'PEXA Workspace',
        'Settlement Figures',
        'Invoice',
        'Settlement',
        'Order on the Agent',
        'Letter',
    ],
];
