name: Deploy on Push

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd ~/landona.com.au
          composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
      - name: Deploy
        run: |
          php artisan migrate --force --seed
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          sudo systemctl restart php8.2-fpm
          sudo systemctl restart nginx
