name: Deploy

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: self-hosted  # Use your self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: List files in directory
        run: ls -l /home/taylor/landona.com.au
      
      - name: Execute deploy script
        run: /home/taylor/landona.com.au/deploy.sh
