name: Deploy

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: self-hosted  # Use your self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy
        run: /home/taylor/landona.com.au/deploy.sh  # Replace with the actual path to your deploy.sh script
